#! /bin/sh
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'DP-3 connected') ]]; then
  xrandr --output DP-0 --primary --mode 1920x1080 --rotate normal --rate 240 --output DP-3 --mode 1920x1080 --rotate normal --right-of DP-0
  fi 
  
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8
#bspc monitor DP-3 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color     "#282A36"
bspc config focused_border_color    "#cba6f7"
bspc config presel_border_color     "#FF79C6"

#Autostart applications
sxhkd &
emacs --daemon &
picom --config $HOME/.config/picom/picom.conf & -b --experimental-backends
nitrogen --restore &
dunst &
~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
~/.config/keyboard.sh &
~/.config/mouse.sh &

#Window Rules
bspc rule -a pavucontrol state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a steam state=floating
bspc rule -a solaar state=floating
bspc rule -a galculator state=floating
bspc rule -a Galculator state=floating
bspc rule -a Emacs state=tiled
