#! /bin/sh
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d          
#bspc monitor -d 󰊠 󰊠 󰊠 󰊠 󰊠 󰊠 󰊠
bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color     "#282A36"
bspc config focused_border_color    "#cba6f7"
bspc config presel_border_color     "#FF79C6"

#Autostart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf & -b --experimental-backends
nitrogen --restore &
dunst &
~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
~/.config/keyboard.sh &

bspc rule -a pavucontrol state=floating
bspc rule -a Pavucontrol state=floating
