;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;==========================================================

[colors]
background = #1E1E2E
background-alt = #44474A
#foreground = #CDD5F4
primary =#cba5f7
secondary =#b3befe 
alert = #FF5554
disabled = #44474A

text = #cdd6f4
subtext0 = #a6adc8
subtext1 = #bac2de

base = #1e1e2e
mantle = #181825
crust = #11111b

[settings]
screenchange-reload = true
pseudo-transparency = true

[bar/bar1]
width = 99.8%
offset-x = 0.1%
height = 28pt
radius = 10
wm-restack = bspwm

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0pt

border-size = 6pt
border-color = 
border-bottom-size = 0pt

padding-left = 2
padding-right = 2

module-margin = 1

#separator = |
#separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font:size=12;2

#modules-left = arch date cpu memory 
#modules-center = xworkspaces
#modules-right = xkeyboard pulseaudio systray 

modules-left = arch bspwm pulseaudio
modules-right = xkeyboard cpu memory date time systray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


[module/arch]
type = custom/text
format = "󰣇"
click-left = "~/.config/rofi/shutdown.sh"
background = ${colors.text} 

[module/systray]
type = internal/tray
tray-size = 60%
format-margin = 2pt
tray-spacing = 2pt

[module/bspwm]
type = internal/xworkspaces
content-background = ${colors.crust}

label-active = %name%
label-active-foreground= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio
interval = 5

format-volume-prefix-foreground = ${colors.primary}
format-volume = <ramp-volume><label-volume>

label-volume = %percentage%%

label-muted = "muted"

label-muted-foreground = ${colors.disabled}

ramp-volume-0 = "  "
ramp-volume-1 = "  "
ramp-volume-2 = "  "
ramp-volume-3 = "  "
ramp-volume-4 = "  "
ramp-volume-5 = "  "
ramp-volume-6 = "  "
ramp-volume-7 = "  "
ramp-volume-8 = "  "
ramp-volume-9 = "  "

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.primary}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "ram: " 
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "cpu: "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/date]
type = internal/date
interval = 1
date =%b-%d
label = %date%
label-foreground = ${colors.primary}
format-prefix = " "

[module/time]
type = internal/date
interval = 1
date = "%I:%M %p"
format-prefix = " "
label-foreground = ${colors.primary}

[network-base]
type = internal/network
format-connected-prefix = 
format-connected =   <label-connected>
format-disconnected = 󰤮 
interval = 5

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = 󰤨  %essid%


[module/eth]
inherit = network-base
interface-type = wired
label-connected = %local_ip%

[module/battery]
type = internal/battery

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-charging = %percentage%%
label-discharging = %percentage%%

ramp-capacity-0 = " " 
ramp-capacity-1 = " " 
ramp-capacity-2 = " " 
ramp-capacity-3 = " " 
ramp-capacity-4 = " " 

animation-charging-0 = " " 
animation-charging-1 = " " 
animation-charging-2 = " " 
animation-charging-3 = " " 
animation-charging-4 = " " 
animation-charging-framerate = 750

animation-discharging-0 = " " 
animation-discharging-1 = " " 
animation-discharging-2 = " " 
animation-discharging-3 = " " 
animation-discharging-4 = " " 
animation-discharging-framerate = 500

; vim:ft=dosini
